const en = {
	header: {
		logo: "Logo",
		more: 'More',
	},
	user: {
		login: "Sign in",
		register: "Sign up",
		hasCount: "Already have an account?",
		account:'Mobile / Mailbox',
		password:'password',
		noCount: "New user? register now",
		"没有账号": "New user?",
		"立即注册": "register now",
		forget: 'Forgot Password',
		logOut: "Sign out",
		logSucc: "Sign in Success",
		resetWord: "Reset password",
		place: {
			userName: "Please enter a user name",
			passWord: "Please enter your password",
			passWordAgain: "Please enter your password again",
			passNotMatch: "The two passwords do not match",
			leader: 'Please enter the inviter',
			Agreement: 'User protocol',
			mnemonic: 'Please enter mnemonic words',
			resetSccu: 'Reset successful',
			miningNum:'Please enter the mining amount',
		},
		switching: 'Switching language(EN)',
		"直接下载":"Direct APP download",
		"返回登录":"Return to login"
	},
	code: {
		error: "error"
	},
	text:{
		"取消":"cancel",
		"确定":"yes",
		"手机账户":"Mobile",
		"邮箱账户":"Mailbox",
		"手机号":"Mobile",
		"邮箱":"Mailbox",
		"验证码":"Verification Code",
		"密码":"Password",
		"确认密码":"Confirm Password",
		"重置密码":"Reset",
		"获取验证码":"send",
		"请填写手机号":"Please fill in the mobile phone number",
		"请填写邮箱地址":"Please fill in the email address",
		"已发送，请注意查收":"has been sent, please pay attention to check",
		"修改成功":"Success",
		"重新发送":"resend",
		
		"手机注册":"Mobile",
		"邮箱注册":"Mailbox",
		"邀请码":"Invitation Code",
		"邀请人必填":"The inviter must fill",
		"注册成功":"Success",
		"切换语言":"Switch Languages",
		
		"交易密码":"Trading Codes",
		
		"个人中心":"Personal Center",
		"账户信息":"Account Information",
		"我的车辆":"My Car",
		"邀请好友":"Invite Friends",
		"公告列表":"Announcement List",
		"关于我们":"About Us",
		"账户与安全":"Account and security",
		"语言切换":"Language Switch",
		"联系客服":"Contact Customer Service",
		"注销登录":"Logout",
		"提示":"Hint",
		"继续注销":"Are you sure you want to continue logout?",
		
		"重置登录密码":"Reset login Password",
		"重置交易密码":"Reset the trading codes",
		
		"资产":"Assets",
		"总资产":"Total assets",
		"资产明细":"Asset breakdown",
		"币种":"Currency",
		"可用":"Available",
		
		"投资":"Investment",
		"兑换":"Exchange",
		"终端兑换队列":"Terminal Exchange Queue",
		"升级我的终端":"Upgrade my terminal",
		
		"中奖":"win the lottery",
		"准时抽奖":"Draw every day at 16:00,19:00 sharp",
		"规则说明":"Rulebook",
		"本金":"Principal",
		"收益率":"Rate of return",
		"获得":"Acquire",
		"点击抽奖":"Lottery",
		"抽奖所得":"The raffle money will be paid immediately. Please go to the assets to check.",
		
		"公告":"NOTICE",
		"更多":"MORE",
		"每天":"Every day",
		"准时抽奖":"draw lottery on time",
		
		"切换车队":"Switching teams",
		"我的车队":"My motorcade",
		"我的车友":"My fellow drivers",
		
		"车友小金库":"Carpool vaults",
		"车友":"Carpool",
		"暂无相关数据":"暂无相关数据",
		
		"总计车队价值":"Total fleet value",
		"可计车队价值":"Imputable fleet value",
		"记录":"Records",
		"兑换排列":"Exchange arrangement",
		"升级车辆":"Upgrade vehicle",
		"抱歉，您未中奖":"I'm sorry, you didn't win",
		"租赁":"rent out"
	},
	mechine:{
		"车辆兑换队列":"Vehicle Exchange Queue",
		"我的队列":"My Line",
		"您当前没有排队兑换车辆":"You are not currently in line for a change of vehicle",
		"车辆兑换总队列":"Vehicle Exchange Master Queue",
		"车辆每日配额":"Daily quota (Sold / Total)",
		"未排队":"Not queued",
		"排队中":"Waiting in line",
		"排队结束":"End of queue",
		
		"我的车辆":"My car",
		"运营中":"Running",
		"已到期":"Expired",
		"车辆级别":"Class of vehicle",
		"可收益价值":"Returnable value",
		"价格":"Price",
		"兑换时间":"Time",
		"升级":"Upgrade",
		"到期时间":"Time",
		"暂无相关数据":"There's no data yet",
		"立即排队兑换":"Line up for the exchange immediately",
		
		"支付":"Payment",
		"兑换数量":"Exchange",
		"辆":"car",
		"总计价值":"total",
		"供需支付":"payment",
		"小时均价":"-hour average price",
		"余额":"Balance",
		"立即支付":"Pay",
		"请输入交易密码":"Please enter your transaction code",
		"忘记交易密码":"Forget the password",
		"确定":"SURE",
		"支付成功":"Success",
		"explain":function(usdt,fcc){
			return'Calculated at the '+usdt+' and '+fcc+' prices at the time of actual payment';
		},
		
		"盈利明细":"Profit details",
		"可收益价值":"Returnable value",
		"已收益价值":"Earned value",
		"已兑换收益价值":"Value of converted proceeds",
		"待兑换收益价值":"Value of proceeds to be converted",
		"一键兑换":"One-click exchange",
		"静态收益":"Static income",
		"今日收益率":"Today's yield",
		"邀请好友收益":"Invite friends proceeds",
		"节点收益":"Node revenue",
		"特别说明":"Special note: the award settlement will be carried out at 12:00 every morning, and the data will be updated after the settlement.",
		"":"",
		"普通":"Normal",
		"初级":"Primary level",
		"中级":"intermediate",
		"高级":"advanced",
		"超级":"super",
		"兑换成功":"Success",
		
		"升级支付":"Upgrade payment",
		"兑换级别":"Exchange level",
		"升级价值":"Upgrade value",
		"共需支付":"Total",
		"立即支付":"payment",
		"已经是最高级别的了":"It's the highest level!",
		"车辆兑换排队总计":"Total vehicle exchange queue",
		
		"请填写交易密码":"Please fill in the transaction code",
		"升级成功":"Success",
		
		"预计收益":"Expected Return",
		"物流收益":"Logistics revenue",
		"分享收益":"Share the profits",
		"全球分红池":"Global Dividend Pool",
		"共价值":"VALUE",
		"未设置交易密码，请设置！":"No transaction password set, please set!"
	},
	about:{
		"关于我们":"About us",
		"当前版本":"version",
		"content": "FCA Foundation, headquartered in Singapore, focuses on global logistics industry investment and building. FCA Free Carrier is the world's first logistics eco-industry chain based on ‘blockchain + Aiot’ technology, through the unification of non-tamper-able distributed books, based on multi-security computing technology, to achieve the encryption of logistics links on the chain; Using the AIOT intelligent network technology, such as RFID, GPS, big data, to track the status of goods, truck location and route in real time; Finally, it provides a ‘one-way’ solution for the whole logistics ecology, which is traceable, safe and reliable, protects the business privacy and data sharing."
	},
	contact:{
		"联系客服":"Call customer service",
		"如需联系":"If you need to contact customer service, please add any of the following Wechat",
		"复制":"copy",
	},
	article:{
		"发表于":"Published on",
		"请求错误":"Request error",
		"暂无信息":"nodata",
		"公告列表":"Announcement ",
		"释放即可刷新":"Release to refresh",
		"刷新成功":"Success",
		"刷新失败":"Failure",
		"没有更多数据":"No more data",
	},
	tabbar:{
		"投资":"Investment",
		"资产":"Assets",
		"抽奖":"Lucky draw",
		"我的":"my",
	},
	update:{
		"检测到新的版本是否下载安装更新":"The new version was detected to download the install update?",
		"不了":"Cancels",
		"下载更新":"Download ",
		"我知道了":"I understand",
		"检查失败":"Check failed！",
		"安装应用":"Installation",
	},
	share:{
		"邀请好友":"Invite your friends",
		"邀请码":"Invitation",
		"已邀请":"Invited",
		"我的邀请人":"My inviter",
		"您的邀请码":"Your invitation code",
		"复制邀请码":"Copy the invitation code",
		"一代业绩":"Level one",
		"二代业绩":"Level twe",
		"旗下全业绩":"All of it",
		"业绩总汇":"Performance summary",
		"好友名称":"Friend name",
		"邀请时间":"Invitation time",
		"好友业绩":"Friend performance",
		"旗下直推业绩":"Direct push results",
		"复制失败":"Failure",
		"特别说明":"In particular",
		"用户注册时":"The user needs to fill in your exclusive invitation code when registering before the user can become your friend.",
		"复制邀请链接":"Copy invitation link",
		"总计车队价值":"Total fleet value",
		"可计车队价值":"Imputable fleet value",
		"保存到相册":"Save to photo album",
		"复制":"copy",
		"生成邀请海报":"Generate an invitation poster",
	},
	asset:{
		"充币记录":"Charge record",
		"复制地址":"Copy address",
		"特别说明":"In particular",
		"state":function(val){
			return 'This is your only unique and unique forwarding address that you can use for multiple charges at the same time. This address prohibits the replenishment of assets other than '+val+' Any other asset replenishment will not be recoverable.'
		},
		"复制失败":"Failure",
		"充值":"Charge",
		"提币":"Withdraw",
		"收支记录":"Record of income and expenditure",
		"无收支记录":"No record of income or expenditure",
		"未知":"Unknown",
		"转账":"Transfer",
		"提币未通过退回":"The coin was not returned",
		"兑换车辆":"Exchange vehicle",
		"升级车辆":"Upgrade vehicle",
		"收益兑换":"Earnings conversion",
		"抽奖":"Lucky draw",
		
		"充币记录":"Charge record",
		"币种":"Currency",
		"地址":"Address",
		"来自":"From",
		"数量":"amount",
		"时间":"Time",
		"编号":"No",
		"提币中":"In the coin",
		"成功":"Success",
		"已拒绝":"Denied",
		"暂无相关数据":"There's no data yet",
		
		"可提币":"",
		"获取失败":"Fetch failed",
		"提币记录":"Withdrawal Record",
		"提币地址":"Withdrawal Address",
		"输入或长按粘贴地址":"Withdrawal Address",
		"最小提币量":"Minimum amount:",
		"手续费":"Service Charge:",
		"验证码":"code",
		"到账数量":"Amount received",
		"stateWithdraw":function(val,coinName){
			return 'Currently, each person can withdraw up to  '+val.withdraw24hMax+' '+coinName+','+
					'per day, with a limit of '+val.withdrawMin+' ~ '+val.withdrawMax+' '+coinName+','+
					'per person per day out-of-station cash handling fee: '+val.withdrawFee+', station transfer handling fee:'+val.transferFee+','+
					'in order to ensure the security of funds, we will carry out manual verification of the cash, please be patient.';
		},
		"手机验证码":"Mobile Code",
		"邮箱验证码":"Mailbox Code",
		"输入":"Please enter ",
		"获取验证码":"SEND CODE",
		
		
		"请填写地址":"Please fill in the address",
		"请填写数量":"Please fill in the quantity",
		"请填写验证码":"Please fill in the quantity",
		"提币申请已提交":"The application for coin withdrawal has been submitted, please wait patiently for approval",
		"已发送":"It has been sent, please pay attention to check",
		"重新发送":"Resend",
		"管理员代充":"Admin replacement",
		"管理员代扣":"Admin Withholding",
		
		"抽奖记录":"Raffle records",
		"账户":"Account",
		"中奖本金":"Winning principal",
		"中奖金额":"Winning amount",
		"极速转账":"transfer",
		
		"地址":"Address",
		"复制":"Copy",
		"chargerState1":'FCA single minimum number of 10, less than the minimum number of recharge will not be accounted for and can not be returned.',
		"chargerState2":'Please be sure to fill in and carefully check the Wallet Address and Memo, which is an important basis for the transfer of your FCA assets. No write, write less or miswrite resulting in the loss of assets, the user should bear.',
	
		"备注":"Notes",
		"withdrawState1":'The minimum number of coins to be withdrawn is 20FCA',
		"withdrawState2":'Please be sure to carefully check whether the target address is correct, otherwise it will lead to withdrawal failure or asset losses, and assets can not be recovered.',
		"withdrawState3":'Please be sure to check carefully whether the Memo is correct, otherwise it will cause the loss of assets and can not be recovered.',
		"withdrawState4":'Make sure your phone is secure against any tampering or leakage of information.',
	},
	nationCode:{
		'376': 'Principality of Andorra',
		'971': 'United Arab Emirates',
		'93': 'Islamic State of Afghanistan',
		'1268': 'Antigua and Barbuda',
		'1264': 'Anguilla',
		'355': 'Republic of Albania',
		'374': 'Republic of Armenia',
		'244': 'Republic of Angola',
		'54': 'Argentine Republic',
		'43': 'Republic of Austria',
		'61': 'Commonwealth of Australia',
		'994': 'Republic of Azerbaijan',
		'387': 'Bosnia and Herzegovina',
		'1246': 'Barbados',
		'880': 'People´s Republic of Bangladesh',
		'32': 'Kingdom of Belgium',
		'226': 'Burkina Faso',
		'359': 'Republic of Bulgaria',
		'973': 'Kingdom of Bahrain',
		'257': 'Republic of Burundi',
		'229': 'Republic of Benin',
		'1441': 'Bermuda',
		'673': 'Negara Brunei Darussalam',
		'591': 'Republic of Bolivia',
		'55': 'Federative Republic of Brazil',
		'1242': 'Commonwealth of The Bahamas',
		'975': 'Kingdom of Bhutan',
		'267': 'Republic of Botswana',
		'375': 'Republic of Belarus',
		'501': 'Belize',
		'1': 'Canada',
		'243': 'Democratic Republic of the Congo',
		'236': 'Central African Republic',
		'242': 'Republic of the Congo',
		'41': 'Swiss Confederation',
		'225': 'Republic of Cote d´Ivoire',
		'56': 'Republic of Chile',
		'237': 'Republic of Cameroon',
		'86': 'People´s Republic of China',
		'57': 'Republic of Colombia',
		'506': 'Republic of Costa Rica',
		'53': 'Republic of Cuba',
		'238': 'Republic of Cape Verde',
		'357': 'Republic of Cyprus',
		'420': 'Czech Republic',
		'49': 'Federal Republic of Germany',
		'253': 'Republic of Djibouti',
		'45': 'Kingdom of Denmark',
		'1767': 'Commonwealth of Dominica',
		'1849': 'Dominican Republic',
		'213': "People's Democratic Republic of Algeria",
		'593': 'Republic of Ecuador',
		'372': 'Republic of Estonia',
		'20': 'Arab Republic of Egypt',
		'291': 'State of Eritrea',
		'34': 'Kingdom of Spain',
		'251': 'Federal Democratic Republic of Ethiopia',
		'358': 'Republic of Finland',
		'679': 'Republic of the Fiji Islands',
		'691': 'Federated States of Micronesia',
		'33': 'French Republic',
		'241': 'Gabonese Republic',
		'44': 'United Kingdom of Great Britain and Northern Ireland',
		'1473': 'Grenada',
		'995': 'Republic of Georgia',
		'233': 'Republic of Ghana',
		'220': 'Republic of The Gambia',
		'224': 'Republic of Guinea',
		'240': 'Republic of Equatorial Guinea',
		'30': 'Hellenic Republic',
		'502': 'Republic of Guatemala',
		'245': 'Republic of Guinea-Bissau',
		'592': 'Co-operative Republic of Guyana',
		'852': 'Hong Kong Special Administrative Region',
		'504': 'Republic of Honduras',
		'385': 'Republic of Croatia',
		'509': 'Republic of Haiti',
		'36': 'Republic of Hungary',
		'62': 'Republic of Indonesia',
		'353': 'Ireland',
		'972': 'State of Israel',
		'91': 'Republic of India',
		'964': 'Republic of Iraq',
		'98': 'Islamic Republic of Iran',
		'354': 'Republic of Iceland',
		'39': 'Italian Republic',
		'1876': 'Jamaica',
		'962': 'Hashemite Kingdom of Jordan',
		'81': 'Japan',
		'254': 'Republic of Kenya',
		'996': 'Kyrgyz Republic',
		'855': 'Kingdom of Cambodia',
		'686': 'Republic of Kiribati',
		'269': 'Union of Comoros',
		'1869': 'Federation of Saint Kitts and Nevis',
		'850': "Democratic People's Republic of Korea",
		'82': 'Republic of Korea',
		'965': 'State of Kuwait',
		'1345': 'Cayman Islands',
		'7': 'Republic of Kazakhstan',
		'856': 'Lao People´s Democratic Republic',
		'961': 'Lebanese Republic',
		'1758': 'Saint Lucia',
		'423': 'Principality of Liechtenstein',
		'94': 'Democratic Socialist Republic of Sri Lanka',
		'231': 'Republic of Liberia',
		'266': 'Kingdom of Lesotho',
		'370': 'Republic of Lithuania',
		'352': 'Grand Duchy of Luxembourg',
		'371': 'Republic of Latvia',
		'218': 'Great Socialist People´s Libyan Arab Jamahiriya',
		'212': 'Kingdom of Morocco',
		'377': 'Principality of Monaco',
		'373': 'Republic of Moldova',
		'382': 'Republic of Montenegro',
		'261': 'Republic of Madagascar',
		'692': 'Republic of the Marshall Islands',
		'389': 'Republic of Macedonia',
		'223': 'Republic of Mali',
		'95': 'Union of Myanmar',
		'976': 'Mongolia',
		'853': 'Macau Special Administrative Region',
		'222': 'Islamic Republic of Mauritania',
		'356': 'Republic of Malta',
		'230': 'Republic of Mauritius',
		'960': 'Republic of Maldives',
		'265': 'Republic of Malawi',
		'52': 'United Mexican States',
		'60': 'Malaysia',
		'258': 'Republic of Mozambique',
		'264': 'Republic of Namibia',
		'227': 'Republic of Niger',
		'234': 'Federal Republic of Nigeria',
		'505': 'Republic of Nicaragua',
		'31': 'Kingdom of the Netherlands',
		'47': 'Kingdom of Norway',
		'977': 'Nepal',
		'674': 'Republic of Nauru',
		'64': 'New Zealand',
		'968': 'Sultanate of Oman',
		'507': 'Republic of Panama',
		'51': 'Republic of Peru',
		'675': 'Independent State of Papua New Guinea',
		'63': 'Republic of the Philippines',
		'92': 'Islamic Republic of Pakistan',
		'48': 'Republic of Poland',
		'970': 'State of Palestine',
		'351': 'Portuguese Republic',
		'680': 'Republic of Palau',
		'595': 'Republic of Paraguay',
		'974': 'State of Qatar',
		'40': 'Romania',
		'381': 'Republic of Serbia',
		'7': 'Russian Federation',
		'250': 'Republic of Rwanda',
		'966': 'Kingdom of Saudi Arabia',
		'677': 'Solomon Islands',
		'248': 'Republic of Seychelles',
		'249': 'Republic of the Sudan',
		'46': 'Kingdom of Sweden',
		'65': 'Republic of Singapore',
		'386': 'Republic of Slovenia',
		'421': 'Slovak Republic',
		'232': 'Republic of Sierra Leone',
		'378': 'Republic of San Marino',
		'221': 'Republic of Senegal',
		'252': 'Somalia',
		'597': 'Republic of Suriname',
		'211': 'Republic of South Sudan',
		'239': 'Democratic Republic of Sao Tome and Principe',
		'503': 'Republic of El Salvador',
		'963': 'Syrian Arab Republic',
		'268': 'Kingdom of Swaziland',
		'235': 'Republic of Chad',
		'228': 'Togolese Republic',
		'66': 'Kingdom of Thailand',
		'992': 'Republic of Tajikistan',
		'670': 'Democratic Republic of Timor-Leste',
		'993': 'Turkmenistan',
		'216': 'Tunisian Republic',
		'676': 'Kingdom of Tonga',
		'90': 'Republic of Turkey',
		'1868': 'Republic of Trinidad and Tobago',
		'688': 'Tuvalu',
		'886': 'Taiwan, China',
		'255': 'United Republic of Tanzania',
		'380': 'Ukraine',
		'256': 'Republic of Uganda',
		'1': 'United States of America',
		'598': 'Oriental Republic of Uruguay',
		'998': 'Republic of Uzbekistan',
		'39': 'State of the Vatican City',
		'1784': 'Saint Vincent and the Grenadines',
		'58': 'Bolivarian Republic of Venezuela',
		'1284': 'British Virgin Islands',
		'1340': 'United States Virgin Islands',
		'84': 'Socialist Republic of Vietnam',
		'678': 'Republic of Vanuatu',
		'685': 'Independent State of Samoa',
		'383': 'The Republic of Kosovo',
		'967': 'Republic of Yemen',
		'27': 'Republic of South Africa',
		'260': 'Republic of Zambia',
		'263': 'Republic of Zimbabwe',
	}
}

export default en;
